### ISSUE TITLE
flush and rtsPin

### ISSUE THREAD

**Issue by DierkJ** [eModbus/eModbus#39]
**RS.485 rx/tx flow control does not work**
I am using ModbusClientRTU() to read Modbus energy meters.  My RS.485 hardware is using an ESP32 pin to control the receive / transmit.  The implementation in RTUtils.cpp RTUutils::send() does not work, because the RTS pin is switched only on for less than a millisecond.  I uncommented serial.flush()...

**Code in RTUtils.cpp, line 110**
```
// serial.flush();
// Toggle rtsPin, if necessary
if (rtsPin >= 0) digitalWrite(rtsPin, LOW);
```
**exchange with:**
```
// 
// Toggle rtsPin, if necessary
if (rtsPin >= 0) {
   serial.flush();
   digitalWrite(rtsPin, LOW);
}
```

**Comment by Miq1** [comment]
I will have a look at this tomorrow.

**Comment by Miq1** [comment]
You are right:
![grafik](https://user-images.githubusercontent.com/25884124/103292730-b4d78780-49ee-11eb-88b7-f25b0c167251.png)

I must confess I had abandoned the non-auto halfduplex modules a while ago, and due to another issue I removed as many ``flush()`` calls as were possible (the issue being that input FIFOs are flushed as well on the ESP32). That should not matter with RTU, so your fix seems to be okay:
![grafik](https://user-images.githubusercontent.com/25884124/103292973-3c24fb00-49ef-11eb-8a1b-d5b0d30fbec6.png)

Thank you, will be added!

**Comment by DierkJ** [comment]
Thanks, perfect.
